12 show reviewed
infoshareacademy/jcszr1-TheForce pull request #23
Opened 2020-08-09 18:36 UTC by marek-wilk

Added ShowReviewed to ReviewService.cs

2020-08-20 20:20 UTC, joanna-bukowska commented on BLL/ReviewService.cs
> +                Console.WriteLine("You haven't reviewed any drinks yet!");
```suggestion
                Console.WriteLine("You haven't reviewed any drinks yet.");
```

2020-08-20 20:25 UTC, joanna-bukowska requested changes

2020-08-20 20:25 UTC, joanna-bukowska commented on BLL/ReviewService.cs
> +                Console.WriteLine("You haven't reviewed any drinks yet!");
Please don't yell on user. :D

2020-08-22 14:58 UTC, wojciechkapko approved these changes

2020-08-22 15:04 UTC, joanna-bukowska approved these changes

2020-08-23 12:56 UTC, merged